package cz.magix.maarifa.ui.composite;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.VerticalLayout;

public class RelationshipFilterComposite extends CustomComponent {
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout bottomToolbatLayout;
	@AutoGenerated
	private Button cancelButton;
	@AutoGenerated
	private Button setButton;
	@AutoGenerated
	private TwinColSelect outgoingTwinColSelect;
	@AutoGenerated
	private TwinColSelect incomingTwinColSelect;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RelationshipFilterComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// incomingTwinColSelect
		incomingTwinColSelect = new TwinColSelect();
		incomingTwinColSelect.setCaption("Incoming relationships");
		incomingTwinColSelect.setImmediate(false);
		incomingTwinColSelect.setWidth("-1px");
		incomingTwinColSelect.setHeight("-1px");
		mainLayout.addComponent(incomingTwinColSelect);
		
		// outgoingTwinColSelect
		outgoingTwinColSelect = new TwinColSelect();
		outgoingTwinColSelect.setCaption("Outgoing relationships");
		outgoingTwinColSelect.setImmediate(false);
		outgoingTwinColSelect.setWidth("-1px");
		outgoingTwinColSelect.setHeight("-1px");
		mainLayout.addComponent(outgoingTwinColSelect);
		
		// bottomToolbatLayout
		bottomToolbatLayout = buildBottomToolbatLayout();
		mainLayout.addComponent(bottomToolbatLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildBottomToolbatLayout() {
		// common part: create layout
		bottomToolbatLayout = new HorizontalLayout();
		bottomToolbatLayout.setImmediate(false);
		bottomToolbatLayout.setWidth("-1px");
		bottomToolbatLayout.setHeight("-1px");
		bottomToolbatLayout.setMargin(false);
		
		// setButton
		setButton = new Button();
		setButton.setCaption("Set");
		setButton.setImmediate(false);
		setButton.setWidth("-1px");
		setButton.setHeight("-1px");
		bottomToolbatLayout.addComponent(setButton);
		
		// cancelButton
		cancelButton = new Button();
		cancelButton.setCaption("Cancel");
		cancelButton.setImmediate(false);
		cancelButton.setWidth("-1px");
		cancelButton.setHeight("-1px");
		bottomToolbatLayout.addComponent(cancelButton);
		
		return bottomToolbatLayout;
	}

}
