package cz.magix.maarifa.ui.composite;

import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.VerticalLayout;

@Component
public class TestComposite extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout buttonToolbarLayout;

	@AutoGenerated
	private Button discardButton;

	@AutoGenerated
	private Button saveButton;

	@AutoGenerated
	private RichTextArea richTextArea_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TestComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// richTextArea_1
		richTextArea_1 = new RichTextArea();
		richTextArea_1.setImmediate(false);
		richTextArea_1.setWidth("100.0%");
		richTextArea_1.setHeight("100.0%");
		mainLayout.addComponent(richTextArea_1);
		mainLayout.setExpandRatio(richTextArea_1, 1.0f);
		
		// buttonToolbarLayout
		buttonToolbarLayout = buildButtonToolbarLayout();
		mainLayout.addComponent(buttonToolbarLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildButtonToolbarLayout() {
		// common part: create layout
		buttonToolbarLayout = new HorizontalLayout();
		buttonToolbarLayout.setImmediate(false);
		buttonToolbarLayout.setWidth("-1px");
		buttonToolbarLayout.setHeight("-1px");
		buttonToolbarLayout.setMargin(false);
		
		// saveButton
		saveButton = new Button();
		saveButton.setCaption("Save");
		saveButton.setImmediate(true);
		saveButton.setWidth("-1px");
		saveButton.setHeight("-1px");
		buttonToolbarLayout.addComponent(saveButton);
		
		// discardButton
		discardButton = new Button();
		discardButton.setCaption("Discard");
		discardButton.setImmediate(true);
		discardButton.setWidth("-1px");
		discardButton.setHeight("-1px");
		buttonToolbarLayout.addComponent(discardButton);
		
		return buttonToolbarLayout;
	}

}
