package cz.magix.maarifa.simple.ui.composite;

import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;


@Component
public class ObjectSearchComposite extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout bottomToolbarLayout;

	@AutoGenerated
	private Button cancelButton;

	@AutoGenerated
	private Button selectButton;

	@AutoGenerated
	private Table resultsTable;

	@AutoGenerated
	private RelationshipFilterBarComposite relationshipFilterBarComposite_1;

	@AutoGenerated
	private TabSheet simpleAdvancedTabs;

	@AutoGenerated
	private VerticalLayout advancedSearchLayout;

	@AutoGenerated
	private VerticalLayout objectFormLayout;

	@AutoGenerated
	private ComboBox objectTypeComboBox;

	@AutoGenerated
	private VerticalLayout simpleSearchLayout;

	@AutoGenerated
	private TextField fullTextSearchField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ObjectSearchComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		cancelButton.addListener(new ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				com.vaadin.ui.Component component = getParent();
				if (component instanceof Window) {
					//Window parentWindow = (Window) component;
				}
			}
		});
	}

	/*
	 * Getters & Setters
	 */
	public Button getCancelButton() {
		return cancelButton;
	}

	public void setCancelButton(Button cancelButton) {
		this.cancelButton = cancelButton;
	}

	public Button getSelectButton() {
		return selectButton;
	}

	public void setSelectButton(Button selectButton) {
		this.selectButton = selectButton;
	}

	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// simpleAdvancedTabs
		simpleAdvancedTabs = buildSimpleAdvancedTabs();
		mainLayout.addComponent(simpleAdvancedTabs);
		
		// relationshipFilterBarComposite_1
		relationshipFilterBarComposite_1 = new RelationshipFilterBarComposite();
		relationshipFilterBarComposite_1.setImmediate(false);
		relationshipFilterBarComposite_1.setWidth("100.0%");
		relationshipFilterBarComposite_1.setHeight("-1px");
		mainLayout.addComponent(relationshipFilterBarComposite_1);
		mainLayout.setComponentAlignment(relationshipFilterBarComposite_1, new Alignment(6));
		
		// resultsTable
		resultsTable = new Table();
		resultsTable.setImmediate(false);
		resultsTable.setWidth("100.0%");
		resultsTable.setHeight("100.0%");
		mainLayout.addComponent(resultsTable);
		mainLayout.setExpandRatio(resultsTable, 1.0f);
		
		// bottomToolbarLayout
		bottomToolbarLayout = buildBottomToolbarLayout();
		mainLayout.addComponent(bottomToolbarLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildSimpleAdvancedTabs() {
		// common part: create layout
		simpleAdvancedTabs = new TabSheet();
		simpleAdvancedTabs.setImmediate(true);
		simpleAdvancedTabs.setWidth("100.0%");
		simpleAdvancedTabs.setHeight("-1px");
		
		// simpleSearchLayout
		simpleSearchLayout = buildSimpleSearchLayout();
		simpleAdvancedTabs.addTab(simpleSearchLayout, "Simple Search", null);
		
		// advancedSearchLayout
		advancedSearchLayout = buildAdvancedSearchLayout();
		simpleAdvancedTabs.addTab(advancedSearchLayout, "Advanced Search", null);
		
		return simpleAdvancedTabs;
	}

	@AutoGenerated
	private VerticalLayout buildSimpleSearchLayout() {
		// common part: create layout
		simpleSearchLayout = new VerticalLayout();
		simpleSearchLayout.setCaption("Simple Search");
		simpleSearchLayout.setImmediate(false);
		simpleSearchLayout.setWidth("100.0%");
		simpleSearchLayout.setHeight("-1px");
		simpleSearchLayout.setMargin(true);
		simpleSearchLayout.setSpacing(true);
		
		// fullTextSearchField
		fullTextSearchField = new TextField();
		fullTextSearchField.setImmediate(false);
		fullTextSearchField.setWidth("-1px");
		fullTextSearchField.setHeight("-1px");
		simpleSearchLayout.addComponent(fullTextSearchField);
		
		return simpleSearchLayout;
	}

	@AutoGenerated
	private VerticalLayout buildAdvancedSearchLayout() {
		// common part: create layout
		advancedSearchLayout = new VerticalLayout();
		advancedSearchLayout.setCaption("Advanced Search");
		advancedSearchLayout.setImmediate(false);
		advancedSearchLayout.setWidth("100.0%");
		advancedSearchLayout.setHeight("-1px");
		advancedSearchLayout.setMargin(true);
		advancedSearchLayout.setSpacing(true);
		
		// objectTypeComboBox
		objectTypeComboBox = new ComboBox();
		objectTypeComboBox.setImmediate(false);
		objectTypeComboBox.setWidth("-1px");
		objectTypeComboBox.setHeight("-1px");
		advancedSearchLayout.addComponent(objectTypeComboBox);
		
		// objectFormLayout
		objectFormLayout = new VerticalLayout();
		objectFormLayout.setImmediate(false);
		objectFormLayout.setWidth("-1px");
		objectFormLayout.setHeight("-1px");
		objectFormLayout.setMargin(false);
		advancedSearchLayout.addComponent(objectFormLayout);
		
		return advancedSearchLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildBottomToolbarLayout() {
		// common part: create layout
		bottomToolbarLayout = new HorizontalLayout();
		bottomToolbarLayout.setImmediate(false);
		bottomToolbarLayout.setWidth("-1px");
		bottomToolbarLayout.setHeight("-1px");
		bottomToolbarLayout.setMargin(false);
		
		// selectButton
		selectButton = new Button();
		selectButton.setCaption("Select");
		selectButton.setImmediate(true);
		selectButton.setWidth("-1px");
		selectButton.setHeight("-1px");
		bottomToolbarLayout.addComponent(selectButton);
		
		// cancelButton
		cancelButton = new Button();
		cancelButton.setCaption("Cancel");
		cancelButton.setImmediate(true);
		cancelButton.setWidth("-1px");
		cancelButton.setHeight("-1px");
		bottomToolbarLayout.addComponent(cancelButton);
		
		return bottomToolbarLayout;
	}

}
