package cz.magix.maarifa.simple.ui.composite;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

public class RelationshipFilterBarComposite extends CustomComponent {
	@AutoGenerated
	private HorizontalLayout mainLayout;

	@AutoGenerated
	private Button clearButton;

	@AutoGenerated
	private Button setButton;

	@AutoGenerated
	private Label filterLabel;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RelationshipFilterBarComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// filterLabel
		filterLabel = new Label();
		filterLabel.setImmediate(false);
		filterLabel.setWidth("-1px");
		filterLabel.setHeight("-1px");
		filterLabel.setValue("Label");
		mainLayout.addComponent(filterLabel);
		mainLayout.setExpandRatio(filterLabel, 1.0f);
		
		// setButton
		setButton = new Button();
		setButton.setCaption("Set...");
		setButton.setImmediate(true);
		setButton.setWidth("-1px");
		setButton.setHeight("-1px");
		mainLayout.addComponent(setButton);
		
		// clearButton
		clearButton = new Button();
		clearButton.setCaption("Clear");
		clearButton.setImmediate(true);
		clearButton.setWidth("-1px");
		clearButton.setHeight("-1px");
		mainLayout.addComponent(clearButton);
		
		return mainLayout;
	}

}
